DROP TABLE "HEALTHCENTER";
DROP TABLE "EXERCISE";
DROP TABLE "LOCATIONCODE";
-- DROP TABLE "NUTRITION";
DROP TABLE "RREPORT";
DROP TABLE "REPLY_LIKE";
DROP TABLE "REPLY";
DROP TABLE "BEMOTICON";
DROP TABLE "BOOKMARK";
DROP TABLE "BOARD";
DROP TABLE "BCATEGORY";
DROP TABLE "DIARY";
DROP TABLE "CART";
DROP TABLE "WISH";
DROP TABLE "ORDER";
--DROP TABLE "PRODUCT";
DROP TABLE "CATEGORY";
DROP TABLE "USERAUTH";
DROP TABLE "MEMBER";
DROP TABLE "LEAVEDMEMBER";


CREATE TABLE "EXERCISE" (
	"EXID"	NUMBER		NOT NULL,
	"EXERCISE"	VARCHAR2(200)		NOT NULL,
	"FIVE_M_KCAL"	NUMBER		NOT NULL,
    "TEN_M_KCAL"	NUMBER		NOT NULL,
    "THIRTY_M_KCAL"	NUMBER		NOT NULL,
    "ONE_H_KCAL"	NUMBER		NOT NULL
);

CREATE TABLE "LEAVEDMEMBER" (
	"LMID"	NUMBER		NOT NULL,
	"MROLE"	CHAR(1)	DEFAULT 'M'	NOT NULL,
	"MEMAIL"	VARCHAR2(100)		NOT NULL,
	"MPW"	VARCHAR2(50)		NOT NULL,
	"MNAME"	VARCHAR2(50)		NOT NULL,
	"MCREATE"	TIMESTAMP	DEFAULT CURRENT_TIMESTAMP	NOT NULL,
	"MUPDATE"	TIMESTAMP	DEFAULT CURRENT_TIMESTAMP	NULL,
	"ENABLED"	CHAR(1)	DEFAULT 'A'	NOT NULL,
	"PROFIMG"	VARCHAR2(1000)	DEFAULT '/resources/profile/img/기본이미지.jpg'	 NOT NULL
);
COMMENT ON COLUMN "LEAVEDMEMBER"."MROLE" IS 'MEMBER, SELLER, ADMIN';
COMMENT ON COLUMN "LEAVEDMEMBER"."MSTATE" IS 'ACTIVE, LEAVE';
COMMENT ON COLUMN "LEAVEDMEMBER"."PROFIMG" IS 'default profileimg';

CREATE TABLE "MEMBER" (
	"MID"	NUMBER		NOT NULL,
	"MROLE"	CHAR(1)	DEFAULT 'M'	NOT NULL,
	"MEMAIL"	VARCHAR2(100)		NOT NULL UNIQUE,
	"MPW"	VARCHAR2(120)		NOT NULL,
	"MNAME"	VARCHAR2(50)		NOT NULL,
	"MCREATE"	TIMESTAMP	DEFAULT CURRENT_TIMESTAMP	NOT NULL,
	"MUPDATE"	TIMESTAMP	DEFAULT CURRENT_TIMESTAMP	NULL,
    "ENABLED"	CHAR(1)	DEFAULT '1'	CHECK(ENABLED='0' OR ENABLED='1') NOT NULL,
	"PROFIMG"	VARCHAR2(1000)	DEFAULT 'https://res.cloudinary.com/doxmm0ofz/image/upload/v1675945711/profile/defaultprofile_rmpnyj.jpg' NOT NULL
);
COMMENT ON COLUMN "MEMBER"."MROLE" IS 'MEMBER, SELLER, ADMIN';
COMMENT ON COLUMN "MEMBER"."MSTATE" IS 'ACTIVE, LEAVE';
COMMENT ON COLUMN "MEMBER"."PROFIMG" IS 'default profileimg';

CREATE TABLE "USERAUTH" (
	"MID"	NUMBER		NOT NULL,
	"AUTHORITY"	VARCHAR2(500)	DEFAULT 'ROLE_USER'	NOT NULL
);

CREATE TABLE "CATEGORY" (
	"CID"	NUMBER		NOT NULL,
	"CNAME"	VARCHAR2(100)	NOT NULL
);

CREATE TABLE "PRODUCT" (
	"PID"	NUMBER		NOT NULL,
	"CID"	NUMBER		NOT NULL,
	"PNAME"	VARCHAR2(500)		NOT NULL,
	"PIMAGE"	VARCHAR2(500)		NOT NULL,
	"PPRICE"	NUMBER		NOT NULL,
	"PSALES"	NUMBER	DEFAULT 0	NULL,
	"PSTOCK"	NUMBER	DEFAULT 0	NULL,
	"PSALE"	NUMBER(2)	DEFAULT 0	NOT NULL,
    "PLINK"     VARCHAR2(500) NOT NULL
);

CREATE TABLE "ORDER" (
	"OID"	NUMBER		NOT NULL,
	"PID"	NUMBER		NOT NULL,
	"MID"	NUMBER		NULL,
    "LMID"	NUMBER		NULL,
	"ODATE"	TIMESTAMP	DEFAULT CURRENT_TIMESTAMP	NOT NULL,
	"OCOUNT"	NUMBER		NOT NULL
);

CREATE TABLE "WISH" (
	"PID"	NUMBER		NOT NULL,
	"MID"	NUMBER		NOT NULL
);

CREATE TABLE "CART" (
	"PID"	NUMBER		NOT NULL,
	"MID"	NUMBER		NOT NULL,
	"PCOUNT"	NUMBER	DEFAULT 1	NOT NULL,
	"CCREATE"	TIMESTAMP	DEFAULT CURRENT_TIMESTAMP	NOT NULL
);

CREATE TABLE "DIARY" (
	"DDATE"	DATE		NOT NULL,
	"MID"	NUMBER		NOT NULL,
	"BREAKFAST"	NUMBER	DEFAULT 0	NULL,
	"BREAKFAST_MENU"	VARCHAR2(200)		NULL,
	"SNACK1"	NUMBER	DEFAULT 0	NULL,
	"SNACK1_MENU"	VARCHAR2(200)		NULL,
	"LUNCH"	NUMBER	DEFAULT 0	NULL,
	"LUNCH_MENU"	VARCHAR2(200)		NULL,
	"SNACK2"	NUMBER	DEFAULT 0	NULL,
	"SNACK2_MENU"	VARCHAR2(200)		NULL,
	"DINNER"	NUMBER	DEFAULT 0	NULL,
	"DINNER_MENU"	VARCHAR2(200)		NULL,
	"SNACK3"	NUMBER	DEFAULT 0	NULL,
	"SNACK3_MENU"	VARCHAR2(200)		NULL,
	"EXERCISE"	NUMBER(4)	DEFAULT 0	NULL,
	"WEIGHT"	NUMBER(5, 2)	DEFAULT 0	NULL
);
COMMENT ON COLUMN "DIARY"."WEIGHT" IS '소수점 2자리까지';

CREATE TABLE "BCATEGORY" (
	"BCID"	NUMBER		NOT NULL,
	"BCNAME"	VARCHAR2(30)		NOT NULL
);

CREATE TABLE "BOARD" (
	"BID"	NUMBER		NOT NULL,
	"BCID"	NUMBER		NOT NULL,
	"MID"	NUMBER		NOT NULL,
	"BTITLE"	VARCHAR2(500)		NOT NULL,
	"BCONTENT"	CLOB		NOT NULL,
	"BPICK"	NUMBER	DEFAULT 0	NOT NULL,
	"BCREATE"	TIMESTAMP	DEFAULT CURRENT_TIMESTAMP	NOT NULL,
	"BUPDATE"	TIMESTAMP	DEFAULT CURRENT_TIMESTAMP	NOT NULL,
	"BSTATE"	CHAR(1)	DEFAULT 'A'	NOT NULL,
    "BVIEWCOUNT"	NUMBER	DEFAULT 0	NOT NULL
);
COMMENT ON COLUMN "BOARD"."BCONTENT" IS 'summernote';
COMMENT ON COLUMN "BOARD"."BSTATE" IS 'ACTIVE, DISABLED';

CREATE TABLE "BOOKMARK" (
	"MID"	NUMBER		NOT NULL,
	"BID"	NUMBER		NOT NULL
);

CREATE TABLE "BEMOTICON" (
	"MID"	NUMBER		NOT NULL,
	"BID"	NUMBER		NOT NULL,
	"EMO"	NUMBER		NOT NULL
);
COMMENT ON COLUMN "BEMOTICON"."EMO" IS '0 ~ 4';

CREATE TABLE "REPLY" (
	"RID"	NUMBER		NOT NULL,
	"BID"	NUMBER		NOT NULL,
	"MID"	NUMBER		NOT NULL,
	"RCONTENT"	VARCHAR2(500)		NOT NULL,
	"RCASE"	NUMBER	DEFAULT 0	NOT NULL,
	"RSEQ"	NUMBER		NOT NULL,
    "RSTATE"	NUMBER	DEFAULT 0	NOT NULL,
    "RCREATE"	TIMESTAMP	DEFAULT  CURRENT_TIMESTAMP	NOT NULL
);
COMMENT ON COLUMN "REPLY"."RCASE" IS '기본 댓글 : 0, 대댓글 : 2,3..';
COMMENT ON COLUMN "REPLY"."RSTATE" IS '채택된 댓글 : 1';

CREATE TABLE "REPLY_LIKE" (
	"RID"	NUMBER		NOT NULL,
	"MID"	NUMBER		NOT NULL
);

CREATE TABLE "RREPORT" (
	"MID"	NUMBER		NOT NULL,
	"RID"	NUMBER		NOT NULL,
	"REPID"	NUMBER		NOT NULL,
	"RCREATE"	TIMESTAMP	DEFAULT CURRENT_TIMESTAMP	NOT NULL
);

CREATE TABLE "NUTRITION" (
	"ID"	NUMBER(6)		NOT NULL,
	"PRODUCT"	VARCHAR2(200)		NOT NULL,
	"LOCBRAND"	VARCHAR2(50)		NULL,
	"SERSIZE"	NUMBER(6, 2)	DEFAULT 0	NULL,
	"CAPUNIT"	VARCHAR2(5)		NOT NULL,
	"KCAL"	NUMBER(8, 2)	DEFAULT 0	NULL,
	"PROTEING"	NUMBER(8, 2)	DEFAULT 0	NULL,
	"FATG"	NUMBER(8, 2)	DEFAULT 0	NULL,
	"CARBOG"	NUMBER(8, 2)	DEFAULT 0	NULL
);

CREATE TABLE "HEALTHCENTER" (
	"HPNUM"	VARCHAR2(15)		NOT NULL,
	"HPLACE"	VARCHAR2(50)		NOT NULL,
	"HADDR"	VARCHAR2(100)		NOT NULL,
	"LID"	NUMBER		NOT NULL
);
COMMENT ON COLUMN "HEALTHCENTER"."LID" IS '0 ~ 13';

CREATE TABLE "LOCATIONCODE" (
    "LID"    NUMBER(2)        NOT NULL,
    "LNAME"    VARCHAR2(60)        NOT NULL
);
COMMENT ON COLUMN "LOCATIONCODE"."LID" IS '0 ~ 13';




ALTER TABLE "LEAVEDMEMBER" ADD CONSTRAINT "PK_LEAVEDMEMBER" PRIMARY KEY (
	"LMID"
);

ALTER TABLE "MEMBER" ADD CONSTRAINT "PK_MEMBER" PRIMARY KEY (
	"MID"
);

ALTER TABLE "USERAUTH" ADD CONSTRAINT "PK_USERAUTH" PRIMARY KEY (
	"MID"
);

ALTER TABLE "CATEGORY" ADD CONSTRAINT "PK_CATEGORY" PRIMARY KEY (
	"CID"
);

ALTER TABLE "PRODUCT" ADD CONSTRAINT "PK_PRODUCT" PRIMARY KEY (
	"PID"
);

ALTER TABLE "ORDER" ADD CONSTRAINT "PK_ORDER" PRIMARY KEY (
	"OID"
);

ALTER TABLE "WISH" ADD CONSTRAINT "PK_WISH" PRIMARY KEY (
	"PID",
	"MID"
);

ALTER TABLE "DIARY" ADD CONSTRAINT "PK_DIARY" PRIMARY KEY (
	"DDATE",
	"MID"
);

ALTER TABLE "CART" ADD CONSTRAINT "PK_CART" PRIMARY KEY (
	"PID",
	"MID"
);

ALTER TABLE "BCATEGORY" ADD CONSTRAINT "PK_BCATEGORY" PRIMARY KEY (
	"BCID"
);

ALTER TABLE "BOARD" ADD CONSTRAINT "PK_BOARD" PRIMARY KEY (
	"BID"
);

ALTER TABLE "BOOKMARK" ADD CONSTRAINT "PK_BOOKMARK" PRIMARY KEY (
	"MID",
	"BID"
);

ALTER TABLE "BEMOTICON" ADD CONSTRAINT "PK_BEMOTICON" PRIMARY KEY (
	"MID",
	"BID"
);

ALTER TABLE "REPLY" ADD CONSTRAINT "PK_REPLY" PRIMARY KEY (
	"RID"
);

ALTER TABLE "REPLY_LIKE" ADD CONSTRAINT "PK_REPLY_LIKE" PRIMARY KEY (
	"RID",
	"MID"
);

ALTER TABLE "RREPORT" ADD CONSTRAINT "PK_RREPORT" PRIMARY KEY (
	"MID",
	"RID"
);

ALTER TABLE "NUTRITION" ADD CONSTRAINT "PK_NUTRITION" PRIMARY KEY (
	"ID"
);

ALTER TABLE "HEALTHCENTER" ADD CONSTRAINT "PK_HEALTHCENTER" PRIMARY KEY (
	"HPNUM"
);

ALTER TABLE "LOCATIONCODE" ADD CONSTRAINT "PK_LID" PRIMARY KEY (
    "LID"
);



ALTER TABLE "USERAUTH" ADD CONSTRAINT "FK_MEMBER_TO_USERAUTH_1" FOREIGN KEY (
	"MID"
)
REFERENCES "MEMBER" (
	"MID"
);

ALTER TABLE "ORDER" ADD CONSTRAINT "FK_PRODUCT_TO_ORDER_1" FOREIGN KEY (
	"PID"
)
REFERENCES "PRODUCT" (
	"PID"
) ON DELETE CASCADE;

ALTER TABLE "ORDER" ADD CONSTRAINT "FK_MEMBER_TO_ORDER_1" FOREIGN KEY (
	"MID"
)
REFERENCES "MEMBER" (
	"MID"
) ON DELETE SET NULL ;

ALTER TABLE "ORDER" ADD CONSTRAINT "FK_LEAVEDMEMBER_TO_ORDER_1" FOREIGN KEY (
	"LMID"
)
REFERENCES "LEAVEDMEMBER" (
	"LMID"
) ON DELETE CASCADE;

ALTER TABLE "WISH" ADD CONSTRAINT "FK_PRODUCT_TO_WISH_1" FOREIGN KEY (
	"PID"
)
REFERENCES "PRODUCT" (
	"PID"
) ON DELETE CASCADE;

ALTER TABLE "WISH" ADD CONSTRAINT "FK_MEMBER_TO_WISH_1" FOREIGN KEY (
	"MID"
)
REFERENCES "MEMBER" (
	"MID"
) ON DELETE CASCADE;

ALTER TABLE "DIARY" ADD CONSTRAINT "FK_MEMBER_TO_DIARY_1" FOREIGN KEY (
	"MID"
)
REFERENCES "MEMBER" (
	"MID"
) ON DELETE CASCADE;

ALTER TABLE "CART" ADD CONSTRAINT "FK_PRODUCT_TO_CART_1" FOREIGN KEY (
	"PID"
)
REFERENCES "PRODUCT" (
	"PID"
) ON DELETE CASCADE;

ALTER TABLE "CART" ADD CONSTRAINT "FK_MEMBER_TO_CART_1" FOREIGN KEY (
	"MID"
)
REFERENCES "MEMBER" (
	"MID"
) ON DELETE CASCADE;

ALTER TABLE "PRODUCT" ADD CONSTRAINT "FK_CATEGORY_TO_PRODUCT_1" FOREIGN KEY (
	"CID"
)
REFERENCES "CATEGORY" (
	"CID"
) ON DELETE CASCADE;

ALTER TABLE "BOARD" ADD CONSTRAINT "FK_BCATEGORY_TO_BOARD_1" FOREIGN KEY (
	"BCID"
)
REFERENCES "BCATEGORY" (
	"BCID"
) ON DELETE CASCADE;

ALTER TABLE "BOARD" ADD CONSTRAINT "FK_MEMBER_TO_BOARD_1" FOREIGN KEY (
	"MID"
)
REFERENCES "MEMBER" (
	"MID"
) ON DELETE CASCADE;

ALTER TABLE "REPLY_LIKE" ADD CONSTRAINT "FK_REPLY_TO_REPLY_LIKE_1" FOREIGN KEY (
	"RID"
)
REFERENCES "REPLY" (
	"RID"
) ON DELETE CASCADE;

ALTER TABLE "REPLY_LIKE" ADD CONSTRAINT "FK_MEMBER_TO_REPLY_LIKE_1" FOREIGN KEY (
	"MID"
)
REFERENCES "MEMBER" (
	"MID"
) ON DELETE CASCADE;

ALTER TABLE "BOOKMARK" ADD CONSTRAINT "FK_MEMBER_TO_BOOKMARK_1" FOREIGN KEY (
	"MID"
)
REFERENCES "MEMBER" (
	"MID"
) ON DELETE CASCADE;

ALTER TABLE "BOOKMARK" ADD CONSTRAINT "FK_BOARD_TO_BOOKMARK_1" FOREIGN KEY (
	"BID"
)
REFERENCES "BOARD" (
	"BID"
) ON DELETE CASCADE;

ALTER TABLE "REPLY" ADD CONSTRAINT "FK_BOARD_TO_REPLY_1" FOREIGN KEY (
	"BID"
)
REFERENCES "BOARD" (
	"BID"
) ON DELETE CASCADE;

ALTER TABLE "REPLY" ADD CONSTRAINT "FK_MEMBER_TO_REPLY_1" FOREIGN KEY (
	"MID"
)
REFERENCES "MEMBER" (
	"MID"
) ON DELETE CASCADE;

ALTER TABLE "BEMOTICON" ADD CONSTRAINT "FK_MEMBER_TO_BEMOTICON_1" FOREIGN KEY (
	"MID"
)
REFERENCES "MEMBER" (
	"MID"
) ON DELETE CASCADE;

ALTER TABLE "BEMOTICON" ADD CONSTRAINT "FK_BOARD_TO_BEMOTICON_1" FOREIGN KEY (
	"BID"
)
REFERENCES "BOARD" (
	"BID"
) ON DELETE CASCADE;

ALTER TABLE "RREPORT" ADD CONSTRAINT "FK_MEMBER_TO_RREPORT_1" FOREIGN KEY (
	"MID"
)
REFERENCES "MEMBER" (
	"MID"
) ON DELETE CASCADE;

ALTER TABLE "RREPORT" ADD CONSTRAINT "FK_REPLY_TO_RREPORT_1" FOREIGN KEY (
	"RID"
)
REFERENCES "REPLY" (
	"RID"
) ON DELETE CASCADE;

ALTER TABLE "HEALTHCENTER" ADD CONSTRAINT "FK_HEALTHCENTER_TO_LID" FOREIGN KEY (
    "LID"
)
REFERENCES "LOCATIONCODE" (
    "LID"
);

CREATE OR REPLACE TRIGGER trg_order_insert
	    BEFORE INSERT ON "ORDER"
	    FOR EACH ROW
	    DECLARE v_pcount NUMBER;
	    BEGIN
	        SELECT PSTOCK INTO v_pcount FROM PRODUCT WHERE PID = :new.PID;
	        IF v_pcount < :new.OCOUNT THEN
	            RAISE_APPLICATION_ERROR(-20001, '재고 수량 초과!!!');
	        END IF;
	    END;
/

CREATE OR REPLACE PROCEDURE insert_order(p_pid NUMBER, p_mid NUMBER, p_ocount NUMBER, p_result OUT NUMBER)
IS 
count_value NUMBER;
BEGIN 
    SELECT PSTOCK INTO count_value FROM PRODUCT WHERE PID =  p_pid;
    IF count_value < p_ocount THEN 
        p_result := 2;
    ELSE 
            INSERT INTO "ORDER" VALUES((SELECT NVL(MAX(OID), 0)+1 FROM "ORDER"), p_pid, p_mid, NULL, SYSDATE, p_ocount);
            p_result := 1;
          END IF;
    EXCEPTION WHEN OTHERS THEN
             p_result := 0;
    END;
/   
    


COMMIT;




